name = input("what is its name?\n> ")
age = input("what is its age?\n> ")
Hometown = input("what is its hometown?\n> ")
species = input("what is its species?\n> ")
occupation = input("what is its occupation?\n> ")
height = input("how tall is it in feet?\n> ")
hair_color = input("what is its hair color?\n> ")
eye_color = input("what is its eye color?\n> ")
clothing = input("what is its clothing it wants to wear?\n> ")
identifying_features = input("what are its identifying features?\n> ")
special_talent = input("what is its special talent?\n> ")
biggest_fear = input("what is its biggest fear?\n> ")
best_friend = input("what is its best friend?\n> ")
personal_goal = input("what is its personal goal?\n> ")
favorite_saying = input("what is its favorite saying?\n> ")

def show_profile(name, age, hometown, species, occupation, height, hair_color, eye_color, clothing, identifying_features, special_talent, biggest_fear, best_friend, personal_goal, favorite_saying):
    print("\nCharacter Profile")
    print("=" * 20)
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Hometown: {hometown}")
    print(f"Species: {species}")
    print(f"Occupation: {occupation}")
    print(f"Height: {height}")
    print(f"Hair Color: {hair_color}")
    print(f"Eye Color: {eye_color}")
    print(f"Clothing: {clothing}")
    print(f"Identifying Features: {identifying_features}")
    print(f"Special Talent: {special_talent}")
    print(f"Biggest Fear: {biggest_fear}")
    print(f"Best Friend: {best_friend}")
    print(f"Personal Goal: {personal_goal}")
    print(f"Favorite Saying: {favorite_saying}")
    print(f"Personal goal: {personal_goal}")

int(age)
float(height)


print( " The name is " + name + " " + name + "is from " + Hometown + "and is a " + species + ". " + name + " is a " + occupation + " and is " + height + " feet tall. " + name + "'s hair color is " + hair_color + ", and their eye color is " + eye_color + ". They are wearing " + clothing + ", and have the following identifying features: " + identifying_features + ". Their special talent is " + special_talent + ", and their biggest fear is" + biggest_fear + ". Their best friend is " + best_friend + ", and their personal goal is " + personal_goal + ". Their favorite saying is " + favorite_saying + ".")