event_name = input("what is the event name?\n> ")
host_name = input("what is your host's name?\n> ")
location = input("what is your location?\n> ")
month = input("what is the month of the event?\n> ")
day = input("what is the day of the event?\n> ")
guest_count = input("how many guests are you expecting?\n> ")
table_count = input("how many tables do you need?\n> ")
chair_count = input("how many chairs do you need?\n> ")
food_budget = input("what is your food budget?\n> ")
decor_budget = input("what is your decor budget?\n> ")
start_time = input("what is your start time?\n> ")
end_time = input("what is your end time?\n> ")
first_activity = input("what is your first activityrom?\n> ")
second_activity = input("what is your second activity?\n> ")
last_activity = input("what is your last activity?\n> ")

def show_profile(event_name, host_name, location, month, day, guest_count, table_count, chair_count, food_budget, decor_budget, start_time, end_time, first_activity, second_activity, last_activity):
    print("\nEvent Profile")
    print("=" * 20)
    print(f"Event Name: {event_name}")
    print(f"Host Name: {host_name}")
    print(f"Location: {location}")
    print(f"Month: {month}")
    print(f"Day: {day}")
    print(f"Guest Count: {guest_count}")
    print(f"Table Count: {table_count}")
    print(f"Chair Count: {chair_count}")
    print(f"Food Budget: {food_budget}")
    print(f"Decor Budget: {decor_budget}")
    print(f"Start Time: {start_time}")
    print(f"End Time: {end_time}")
    print(f"First Activity: {first_activity}")
    print(f"Second Activity: {second_activity}")
    print(f"Last Activity: {last_activity}")


int(day)
int(guest_count)
int(table_count)
int(chair_count)
float(food_budget)
float(decor_budget)

print( "The event name is " + event_name + ", hosted by " + host_name + ", at " + location + ". The event is on " + month + " " + day + ". You are expecting " + guest_count + " guests. You need " + table_count + " tables and " + chair_count + " chairs. Your food budget is $" + food_budget + " and your decor budget is $" + decor_budget + ". The event starts at " + start_time + " and ends at " + end_time + ". Your first activity is " + first_activity + ", followed by " + second_activity + ", and ending with " + last_activity)