name = input("what is your name?\n> ")
age = input("what is your age?\n> ")
Hometown = input("what is your hometown?\n> ")
food = input("what is your favorite food?\n> ")
hobby = input("what is your favorite hobby?\n> ")
school = input("what school do you go to?\n> ")
grade = input("what grade are you in?\n> ")
subject = input("what is your favorite subject?\n> ")
graduate = input("what year do you graduate?\n> ")
study_hours = input("how many hours a week do you study?\n> ")
dream_job = input("what is your dream job?\n> ")
skill_to_learn = input("what skill do you want to learn?\n> ")
place_to_visit = input("what place do you want to visit?\n> ")
personal_goal = input("what is your personal goal?\n> ")
school_goal = input("what is your school goal?\n> ")

def show_profile(name, age, hometown, food, hobby, school, grade, subject, graduate, study_hours, dream_job, skill_to_learn, place_to_visit, personal_goal, school_goal):
    print("\nStudent Profile")
    print("=" * 20)
    print(f"Name: {name}")
    print(f"Age: {age}")
    print(f"Hometown: {hometown}")
    print(f"Favorite food: {food}")
    print(f"Favorite hobby: {hobby}")
    print(f"School: {school}")
    print(f"Grade: {grade}")
    print(f"Favorite subject: {subject}")
    print(f"Graduation year: {graduate}")
    print(f"Study hours per week: {study_hours}")
    print(f"Dream job: {dream_job}")
    print(f"Skill to learn: {skill_to_learn}")
    print(f"Place to visit: {place_to_visit}")
    print(f"Personal goal: {personal_goal}")
    print(f"School goal: {school_goal}")

int(age)
int(grade)
int(graduate)
float(study_hours)

print( "Your name is " + name + ", you are " + age + " years old, and you are from " + Hometown + ". Your favorite food is " + food + ", and your favorite hobby is " + hobby + ". You go to " + school + ", and you are in grade " + grade + ". Your favorite subject is " + subject + ", and you will graduate in the year " + graduate + ". You study for " + study_hours + " hours a week. Your dream job is to be a " + dream_job + ", and you want to learn the skill of " + skill_to_learn + ". You want to visit " + place_to_visit + ", and your personal goal is to " + personal_goal + ". Your school goal is to " + school_goal)

