name = input("what is your name?\n> ")
destination = input("what is your destination?\n> ")
departure_month = input("what is your departure month?\n> ")
departure_day = input("what is your departure day?\n> ")
trip_length = input("how long is your trip?\n> ")
transportation_type = input("what is your preferred transportation?\n> ")
ticket_price = input("what is the price of your ticket?\n> ")
hotel_name = input("what is the name of your preferred hotel?\n> ")
room_price = input("what is the price of your room?\n> ")
number_of_rooms = input("how many rooms do you need?\n> ")
activity_1 = input("what is your first activity you want to do?\n> ")
activity_2 = input("what is your second activity you want to do?\n> ")
activity_3 = input("what is your third activity you want to do?\n> ")
spending_budget = input("what is your spending budget?\n> ")
souviner_budget = input("what is your souviner budget?\n> ")
#W.I.P. - Work in Progress
def show_profile(name, destination, departure_month, departure_day, trip_length, transportation_type, ticket_price, hotel_name, room_price, number_of_rooms, activity_1, activity_2, activity_3, spending_budget, souviner_budget):
    print("\nStudent Profile")
    print("=" * 20)
    print(f"Name: {name}")
    print(f"Destination: {destination}")
    print(f"Departure Month: {departure_month}")
    print(f"Departure Day: {departure_day}")
    print(f"Trip Length: {trip_length}")
    print(f"Transportation Type: {transportation_type}")
    print(f"Ticket Price: {ticket_price}")
    print(f"Hotel Name: {hotel_name}")
    print(f"Room Price: {room_price}")
    print(f"Number of Rooms: {number_of_rooms}")
    print(f"Activity 1: {activity_1}")
    print(f"Activity 2: {activity_2}")
    print(f"Activity 3: {activity_3}")
    print(f"Spending Budget: {spending_budget}")
    print(f"Souvenir Budget: {souviner_budget}")


int(departure_day)
int(departure_month)
int(trip_length)
int(number_of_rooms)
float(spending_budget)
float(souviner_budget)

print( "Your name is " + name + ", your destination is " + destination + ", and you are there for " + trip_length + ". You depart on " + departure_day + ", in the month of " + departure_month  + "you will travel in a" + transportation_type + ". the tickets cost " + ticket_price + ", in the hotel of " + hotel_name + ". The hotel price is " + room_price + ", and you will need " + number_of_rooms + "rooms. " " Your first acitivity is " + activity_1 + " your second activity is " + activity_2 + ", and your third activity is " + activity_3 + ". Your spending budget is " + spending_budget + ", and your souviner_budget is " + souviner_budget + ". Thank you for the information! Have fun at your trip to " + destination + " ! ")